name: Jar

on:
  workflow_run:
    workflows: [ "test" ]
    branches: [ "master" ]
    types:
      - completed

jobs:
  package-jar:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Fail if test failed
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: exit 1
      - name: Set up JDK24
        uses: actions/setup-java@v4
        with:
          java-version: '24'
          distribution: 'temurin'
          cache: maven
      - name: Package with maven
        run: mvn -B package --file pom.xml