name: Compile

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - '.github/**'
      - '.idea/**'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Build with maven
        run: mvn -B compile --file pom.xml