name: Tests

on:
  workflow_run:
    workflows: [ "compile" ]
    branches: [ "master" ]
    types:
      - completed

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Fail if compile failed
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: exit 1
      - name: Set up JDK23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Test with maven
        run: mvn -B test --file pom.xml