name: Jar

env:
  bundled: jar-with-dependencies

on:
  workflow_run:
    workflows: [ "tests" ]
    branches: [ "master" ]
    types:
      - completed

jobs:
  package-jar:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - name: Fail if test failed
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: exit 1
      - name: Set up JDK23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Jar
        run: mvn -B package --file pom.xml
      - name: Bundled Jar
        run: mvn -B compile assembly:single --file pom.xml
      - name: Set project properties in env
        run: |
          echo "version=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec)" >> $GITHUB_ENV
          echo "name=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec)" >> $GITHUB_ENV
          echo "today=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Rename Jars
        run: |
          mv target/${{ env.name }}-${{ env.version }}.jar ${{ env.name }}-${{ env.today }}.jar
          mv target/${{ env.name }}-${{ env.version }}-${{ env.bundled }}.jar ${{ env.name }}-${{ env.today }}-${{ env.bundled }}.jar
      - name: Make dev Release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: "${{ secrets.RELEASE }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development Build"
          files: |
            ${{ env.name }}-${{ env.today }}.jar
            ${{ env.name }}-${{ env.today }}-${{ env.bundled }}.jar